# Generated by Django 6.1.1 on 2026-09-08 00:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('due_date', models.DateField()),
                ('advance_notice_days', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(365)])),
                ('recurrence', models.CharField(choices=[('ONCE', 'Once'), ('MONTHLY', 'Monthly'), ('EVERY_TWO_MONTHS', 'Every two months'), ('YEARLY', 'Yearly')], default='ONCE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('next_index', models.PositiveIntegerField(default=1, editable=False)),
                ('next_notice_date', models.DateField(db_index=True, editable=False, null=True)),
                ('last_scheduled_at', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_staff_reminders', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_staff_reminders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReminderOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('notice_date', models.DateField(db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occurrences', to='staff_reminders.reminder')),
            ],
            options={
                'ordering': ['due_date', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='reminder',
            constraint=models.CheckConstraint(condition=models.Q(('advance_notice_days__lte', 365)), name='reminder_notice_max365'),
        ),
        migrations.AddConstraint(
            model_name='reminderoccurrence',
            constraint=models.UniqueConstraint(fields=('reminder', 'index'), name='reminder_occurrence_index_unique'),
        ),
        migrations.AddConstraint(
            model_name='reminderoccurrence',
            constraint=models.UniqueConstraint(fields=('reminder', 'due_date'), name='reminder_occurrence_date_unique'),
        ),
        migrations.AddConstraint(
            model_name='reminderoccurrence',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('completed_by__isnull', True)), models.Q(('completed_at__isnull', False), ('completed_by__isnull', False)), _connector='OR'), name='reminder_completion_pair'),
        ),
    ]
