package com.naveenhospital.medtrack.core.designsystem

import androidx.compose.ui.graphics.Color

object MedtrackColors {
    val Ink = Color(0xFF0F172A)
    val InkSoft = Color(0xFF334155)
    val Muted = Color(0xFF64748B)
    val Faint = Color(0xFF94A3B8)
    val Surface = Color(0xFFF4F6FA)
    val SurfaceAlt = Color(0xFFEFF2F7)
    val Card = Color(0xFFFFFFFF)
    val Border = Color(0xFFE7ECF3)
    val Primary = Color(0xFF2563EB)
    val PrimaryDark = Color(0xFF1D4ED8)
    val PrimaryDeep = Color(0xFF1E3A8A)
    val PrimarySoft = Color(0xFFEFF4FF)
    val Navy = Color(0xFF101828)
    val Success = Color(0xFF16A34A)
    val SuccessSoft = Color(0xFFE8F6EE)
    val Warning = Color(0xFFC77A12)
    val WarningSoft = Color(0xFFFBF1E0)
    val Danger = Color(0xFFDC2626)
    val DangerSoft = Color(0xFFFCEBEB)
    val Anc = Color(0xFF0E9A6C)
    val Surgery = Color(0xFFC77A12)
    val Medicine = Color(0xFF5B53D6)
    val CustomRehab = Color(0xFF0E7490)
    val VitalOk = Color(0xFF0E9A6C)
    val VitalOkSoft = Color(0xFFE7F6F0)
    val VitalHigh = Color(0xFFC77A12)
    val VitalHighSoft = Color(0xFFFBF1E0)
    val VitalCritical = Color(0xFFDC2626)
    val VitalCriticalSoft = Color(0xFFFCEBEB)
}
