from django.urls import path

from .views import (
    AddCallLogView,
    AddCaseNoteView,
    CaseCreateView,
    CaseDetailView,
    CaseVitalsDetailView,
    CaseListView,
    CaseAutocompleteView,
    CaseUpdateView,
    DashboardView,
    DatabaseManagementSettingsView,
    RecentCasesView,
    RecentCaseUpdateView,
    VitalEntryCreateView,
    VitalEntryUpdateView,
    ThemeSettingsView,
    UniversalCaseSearchView,
    AdminSettingsView,
    ChangelogView,
    DeviceAccessSettingsView,
    SeedMockDataSettingsView,
    UserManagementSettingsView,
    TaskCreateView,
    TaskQuickCompleteView,
    TaskQuickNoteView,
    TaskQuickRescheduleView,
    TaskUpdateView,
)

app_name = "patients"

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path("recent/", RecentCasesView.as_view(), name="recent_cases"),
    path("recent/<int:pk>/", RecentCaseUpdateView.as_view(), name="recent_case_update"),
    path("settings/", AdminSettingsView.as_view(), name="settings"),
    path("settings/database/", DatabaseManagementSettingsView.as_view(), name="settings_database"),
    path("settings/device-access/", DeviceAccessSettingsView.as_view(), name="settings_device_access"),
    path("settings/theme/", ThemeSettingsView.as_view(), name="settings_theme"),
    path("settings/users/", UserManagementSettingsView.as_view(), name="settings_user_management"),
    path("settings/changelog/", ChangelogView.as_view(), name="changelog"),
    path("settings/seed-mock-data/", SeedMockDataSettingsView.as_view(), name="settings_seed_mock_data"),
    path("cases/", CaseListView.as_view(), name="case_list"),
    path("cases/autocomplete/", CaseAutocompleteView.as_view(), name="case_autocomplete"),
    path("cases/universal-search/", UniversalCaseSearchView.as_view(), name="universal_case_search"),
    path("cases/new/", CaseCreateView.as_view(), name="case_create"),
    path("cases/<int:pk>/", CaseDetailView.as_view(), name="case_detail"),
    path("cases/<int:pk>/vitals/", CaseVitalsDetailView.as_view(), name="case_vitals"),
    path("cases/<int:pk>/edit/", CaseUpdateView.as_view(), name="case_edit"),
    path("cases/<int:pk>/tasks/new/", TaskCreateView.as_view(), name="task_create"),
    path("cases/<int:pk>/vitals/new/", VitalEntryCreateView.as_view(), name="vitals_create"),
    path("tasks/<int:pk>/edit/", TaskUpdateView.as_view(), name="task_edit"),
    path("tasks/<int:pk>/quick-complete/", TaskQuickCompleteView.as_view(), name="task_quick_complete"),
    path("tasks/<int:pk>/quick-reschedule/", TaskQuickRescheduleView.as_view(), name="task_quick_reschedule"),
    path("tasks/<int:pk>/quick-note/", TaskQuickNoteView.as_view(), name="task_quick_note"),
    path("vitals/<int:pk>/edit/", VitalEntryUpdateView.as_view(), name="vitals_edit"),
    path("cases/<int:pk>/notes/new/", AddCaseNoteView.as_view(), name="case_note_create"),
    path("cases/<int:pk>/calls/new/", AddCallLogView.as_view(), name="case_call_create"),
]
