from django.urls import path

from .views import (
    AddCallLogView,
    AddCaseNoteView,
    CategorySettingsView,
    CaseCreateView,
    CaseCreatePreviewView,
    CaseCreateIdentityCheckView,
    CaseManagementSettingsView,
    CaseDetailView,
    CaseVitalsDetailView,
    CaseListView,
    CaseAutocompleteView,
    QuickCaseCreateView,
    CaseUpdateView,
    CaseUpdatePreviewView,
    CaseUpdateIdentityCheckView,
    DashboardView,
    DatabaseManagementSettingsView,
    UpcomingCallsBulkLogView,
    UpcomingCallsView,
    RecentCasesView,
    RecentCaseUpdateView,
    PatientDetailView,
    PatientListView,
    PatientMergeView,
    PatientSearchView,
    PatientUpdateView,
    VitalEntryCreateView,
    VitalEntryUpdateView,
    ThemeSettingsView,
    UniversalCaseSearchView,
    AdminSettingsView,
    ChangelogView,
    DeviceAccessSettingsView,
    SeedMockDataSettingsView,
    UserManagementSettingsView,
    TaskCreateView,
    TaskQuickCompleteView,
    TaskQuickNoteView,
    TaskQuickReopenView,
    TaskQuickRescheduleView,
    TaskUpdateView,
    ThemeIconMockupView,
)

app_name = "patients"

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path("calls/upcoming/", UpcomingCallsView.as_view(), name="calls_upcoming"),
    path("calls/upcoming/bulk-log/", UpcomingCallsBulkLogView.as_view(), name="calls_upcoming_bulk_log"),
    path("recent/", RecentCasesView.as_view(), name="recent_cases"),
    path("recent/<int:pk>/", RecentCaseUpdateView.as_view(), name="recent_case_update"),
    path("patients/search/", PatientSearchView.as_view(), name="patient_search"),
    path("patients/", PatientListView.as_view(), name="patient_list"),
    path("patients/<int:pk>/", PatientDetailView.as_view(), name="patient_detail"),
    path("patients/<int:pk>/edit/", PatientUpdateView.as_view(), name="patient_edit"),
    path("patients/<int:pk>/merge/", PatientMergeView.as_view(), name="patient_merge"),
    path("settings/", AdminSettingsView.as_view(), name="settings"),
    path("settings/categories/", CategorySettingsView.as_view(), name="settings_categories"),
    path("settings/case-management/", CaseManagementSettingsView.as_view(), name="settings_case_management"),
    path("settings/database/", DatabaseManagementSettingsView.as_view(), name="settings_database"),
    path("settings/device-access/", DeviceAccessSettingsView.as_view(), name="settings_device_access"),
    path("settings/theme/", ThemeSettingsView.as_view(), name="settings_theme"),
    path("settings/theme/icon-mockup/", ThemeIconMockupView.as_view(), name="settings_theme_icon_mockup"),
    path("settings/users/", UserManagementSettingsView.as_view(), name="settings_user_management"),
    path("settings/changelog/", ChangelogView.as_view(), name="changelog"),
    path("settings/seed-mock-data/", SeedMockDataSettingsView.as_view(), name="settings_seed_mock_data"),
    path("cases/", CaseListView.as_view(), name="case_list"),
    path("cases/autocomplete/", CaseAutocompleteView.as_view(), name="case_autocomplete"),
    path("cases/universal-search/", UniversalCaseSearchView.as_view(), name="universal_case_search"),
    path("cases/new/", CaseCreateView.as_view(), name="case_create"),
    path("cases/new/preview/", CaseCreatePreviewView.as_view(), name="case_create_preview"),
    path("cases/new/identity-check/", CaseCreateIdentityCheckView.as_view(), name="case_create_identity_check"),
    path("cases/quick-entry/", QuickCaseCreateView.as_view(), name="case_quick_create"),
    path("cases/<int:pk>/", CaseDetailView.as_view(), name="case_detail"),
    path("cases/<int:pk>/vitals/", CaseVitalsDetailView.as_view(), name="case_vitals"),
    path("cases/<int:pk>/edit/", CaseUpdateView.as_view(), name="case_edit"),
    path("cases/<int:pk>/edit/preview/", CaseUpdatePreviewView.as_view(), name="case_edit_preview"),
    path("cases/<int:pk>/edit/identity-check/", CaseUpdateIdentityCheckView.as_view(), name="case_edit_identity_check"),
    path("cases/<int:pk>/tasks/new/", TaskCreateView.as_view(), name="task_create"),
    path("cases/<int:pk>/vitals/new/", VitalEntryCreateView.as_view(), name="vitals_create"),
    path("tasks/<int:pk>/edit/", TaskUpdateView.as_view(), name="task_edit"),
    path("tasks/<int:pk>/quick-reopen/", TaskQuickReopenView.as_view(), name="task_quick_reopen"),
    path("tasks/<int:pk>/quick-complete/", TaskQuickCompleteView.as_view(), name="task_quick_complete"),
    path("tasks/<int:pk>/quick-reschedule/", TaskQuickRescheduleView.as_view(), name="task_quick_reschedule"),
    path("tasks/<int:pk>/quick-note/", TaskQuickNoteView.as_view(), name="task_quick_note"),
    path("vitals/<int:pk>/edit/", VitalEntryUpdateView.as_view(), name="vitals_edit"),
    path("cases/<int:pk>/notes/new/", AddCaseNoteView.as_view(), name="case_note_create"),
    path("cases/<int:pk>/calls/new/", AddCallLogView.as_view(), name="case_call_create"),
]
