# Generated by Django 5.0 on 2026-02-24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("O", "Other"),
                            ("U", "Unspecified"),
                        ],
                        max_length=1,
                    ),
                ),
                ("phone", models.CharField(blank=True, db_index=True, max_length=32)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("emergency_contact_name", models.CharField(blank=True, max_length=200)),
                ("emergency_contact_phone", models.CharField(blank=True, max_length=32)),
                ("notes", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["last_name", "first_name", "id"]},
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["last_name", "first_name"], name="patients_pa_last_na_1b32a7_idx"),
        ),
    ]
