# Generated by Django 5.2.11 on 2026-02-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_case_caseactivitylog_departmentconfig_task_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="edd",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="lmp",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="review_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="review_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MONTHLY", "Monthly"),
                    ("QUARTERLY", "Every 3 months"),
                    ("HALF_YEARLY", "Every 6 months"),
                    ("YEARLY", "Yearly"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="surgery_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="surgery_done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="case",
            name="surgical_pathway",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PLANNED_SURGERY", "Planned for surgery"),
                    ("SURVEILLANCE", "Surveillance only"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="frequency_label",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
