# Generated by Django 5.2.11 on 2026-02-24 13:30

from django.conf import settings
from django.db import migrations, models


def backfill_names_and_roles(apps, schema_editor):
    Case = apps.get_model("patients", "Case")
    RoleSetting = apps.get_model("patients", "RoleSetting")

    for case in Case.objects.all():
        if case.patient_name and (not case.first_name and not case.last_name):
            parts = case.patient_name.split(" ", 1)
            case.first_name = parts[0]
            case.last_name = parts[1] if len(parts) > 1 else ""
            case.save(update_fields=["first_name", "last_name"])

    defaults = {
        "Admin": dict(can_case_create=True, can_case_edit=True, can_task_create=True, can_task_edit=True, can_note_add=True, can_manage_settings=True),
        "Doctor": dict(can_case_create=True, can_case_edit=True, can_task_create=True, can_task_edit=True, can_note_add=True),
        "Reception": dict(can_case_create=True, can_case_edit=True, can_task_create=True, can_note_add=True),
        "Nurse": dict(can_task_edit=True, can_note_add=True),
        "Caller": dict(can_note_add=True),
    }
    for role_name, perms in defaults.items():
        RoleSetting.objects.get_or_create(role_name=role_name, defaults=perms)


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0004_seed_default_departments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role_name", models.CharField(max_length=50, unique=True)),
                ("can_case_create", models.BooleanField(default=False)),
                ("can_case_edit", models.BooleanField(default=False)),
                ("can_task_create", models.BooleanField(default=False)),
                ("can_task_edit", models.BooleanField(default=False)),
                ("can_note_add", models.BooleanField(default=False)),
                ("can_manage_settings", models.BooleanField(default=False)),
            ],
            options={"ordering": ["role_name"]},
        ),
        migrations.AddField(model_name="case", name="first_name", field=models.CharField(default="", max_length=100)),
        migrations.AddField(model_name="case", name="last_name", field=models.CharField(default="", max_length=100)),
        migrations.AlterField(model_name="case", name="patient_name", field=models.CharField(blank=True, max_length=200)),
        migrations.AddIndex(model_name="case", index=models.Index(fields=["first_name", "last_name"], name="patients_ca_first_n_02a940_idx")),
        migrations.RunPython(backfill_names_and_roles, migrations.RunPython.noop),
    ]
