# Generated by Django 5.2.11 on 2026-02-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0005_rolesetting_case_first_name_case_last_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="usg_edd",
            field=models.DateField(blank=True, null=True),
        ),
    ]
