# Generated by Django 5.2.11 on 2026-02-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0006_case_usg_edd"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FEMALE", "Female"),
                    ("MALE", "Male"),
                    ("OTHER", "Other"),
                    ("UNKNOWN", "Unknown"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="place",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
