# Generated by Django 5.2.11 on 2026-02-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0007_case_date_of_birth_case_gender_case_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="abortions",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="age",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="alternate_phone_number",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="case",
            name="diagnosis",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="case",
            name="gravida",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="high_risk",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="case",
            name="living",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="ncd_flags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="case",
            name="para",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="referred_by",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
