# Generated by Django 5.2.11 on 2026-02-25 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_case_abortions_case_age_case_alternate_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='case',
            name='patients_ca_uhid_991737_idx',
        ),
        migrations.RemoveIndex(
            model_name='case',
            name='patients_ca_phone_n_a0e380_idx',
        ),
    ]
