# Generated by Django 5.2.11 on 2026-02-26 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0009_remove_case_patients_ca_uhid_991737_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("ANSWERED_CONFIRMED_VISIT", "Answered - Confirmed visit"),
                            ("ANSWERED_UNCERTAIN", "Answered - Uncertain"),
                            ("NO_ANSWER", "No answer"),
                            ("SWITCHED_OFF", "Switched off"),
                            ("CALL_REJECTED", "Call rejected"),
                            ("INVALID_NUMBER", "Invalid number"),
                            ("PATIENT_SHIFTED", "Patient shifted"),
                            ("PATIENT_DECLINED", "Patient declined"),
                            ("RUDE_BEHAVIOR", "Rude behavior"),
                            ("CALL_BACK_LATER", "Call back later"),
                        ],
                        max_length=40,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_logs",
                        to="patients.case",
                    ),
                ),
                (
                    "staff_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="call_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="call_logs",
                        to="patients.task",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["case", "-created_at"], name="pat_call_case_created_idx"
                    ),
                    models.Index(fields=["outcome"], name="pat_call_outcome_idx"),
                ],
            },
        ),
    ]
