# Generated by Django 5.2.11 on 2026-02-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0010_calllog"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="anc_high_risk_reasons",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
