# Generated by Django 5.2.11 on 2026-03-03 16:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_rch_bypass_for_existing_anc_cases(apps, schema_editor):
    Case = apps.get_model("patients", "Case")
    Case.objects.filter(category__name__iexact="ANC", rch_number="").update(rch_bypass=True)


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0011_case_anc_high_risk_reasons"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="rch_bypass",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="case",
            name="rch_number",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.CreateModel(
            name="VitalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "bp_systolic",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "bp_diastolic",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("pr", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("spo2", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "hemoglobin",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vitals",
                        to="patients.case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_vitals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_vitals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["case", "-recorded_at"],
                        name="pat_vitals_case_recorded_idx",
                    )
                ],
            },
        ),
        migrations.RunPython(backfill_rch_bypass_for_existing_anc_cases, migrations.RunPython.noop),
    ]
