# Generated by Django 5.2.12 on 2026-03-05 22:27

import re

from django.db import migrations, models


def _default_category_theme(name):
    letters_only = re.sub(r"[^A-Z]", "", (name or "").upper())
    if letters_only == "ANC":
        return {"bg": "#d1e7dd", "text": "#0f5132"}
    if letters_only == "SURGERY":
        return {"bg": "#fff3cd", "text": "#664d03"}
    if letters_only == "NONSURGICAL":
        return {"bg": "#e2e3e5", "text": "#41464b"}
    return {"bg": "#e2e3e5", "text": "#41464b"}


def seed_theme_defaults(apps, schema_editor):
    DepartmentConfig = apps.get_model("patients", "DepartmentConfig")
    ThemeSettings = apps.get_model("patients", "ThemeSettings")

    for department in DepartmentConfig.objects.all():
        default_theme = _default_category_theme(department.name)
        department.theme_bg_color = default_theme["bg"]
        department.theme_text_color = default_theme["text"]
        department.save(update_fields=["theme_bg_color", "theme_text_color"])

    ThemeSettings.objects.update_or_create(pk=1, defaults={"tokens": {}})


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0012_case_rch_bypass_case_rch_number_vitalentry"),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='departmentconfig',
            name='theme_bg_color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='departmentconfig',
            name='theme_text_color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.RunPython(seed_theme_defaults, noop_reverse),
    ]
