# Generated by Django 5.2.11 on 2026-03-05 17:50

from django.db import migrations, models
from django.db.models import Q


SYSTEM_NOTE_PREFIXES = (
    "Case created with ",
    "Case status changed:",
    "Cancelled ",
    "RCH reminder scheduled for ",
    "RCH number captured.",
    "RCH removed.",
    "RCH still pending.",
    "Task created:",
    "Task updated:",
    "Mock case seeded with scenario ",
    "Vitals entry recorded.",
    "Vitals entry updated.",
)


def backfill_case_activity_event_type(apps, schema_editor):
    CaseActivityLog = apps.get_model("patients", "CaseActivityLog")

    CaseActivityLog.objects.filter(task_id__isnull=False).update(event_type="TASK")
    CaseActivityLog.objects.filter(note__startswith="Call outcome logged:").update(event_type="CALL")

    system_note_query = Q()
    for prefix in SYSTEM_NOTE_PREFIXES:
        system_note_query |= Q(note__startswith=prefix)

    CaseActivityLog.objects.filter(event_type="SYSTEM").exclude(system_note_query).update(event_type="NOTE")


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0012_case_rch_bypass_case_rch_number_vitalentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="caseactivitylog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("SYSTEM", "System"),
                    ("TASK", "Task"),
                    ("NOTE", "Note"),
                    ("CALL", "Call"),
                ],
                default="SYSTEM",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="caseactivitylog",
            index=models.Index(
                fields=["case", "event_type", "-created_at"],
                name="pat_act_case_type_created_idx",
            ),
        ),
        migrations.RunPython(backfill_case_activity_event_type, migrations.RunPython.noop),
    ]
