# Generated by Django 5.2.12 on 2026-03-15 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('patients', '0014_merge_20260305_2303'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceApprovalPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_groups', models.ManyToManyField(blank=True, related_name='device_approval_policies', to='auth.group')),
                ('target_users', models.ManyToManyField(blank=True, related_name='device_approval_policies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffDeviceCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REVOKED', 'Revoked')], default='PENDING', max_length=16)),
                ('device_label', models.CharField(max_length=120)),
                ('credential_id', models.CharField(max_length=255, unique=True)),
                ('public_key', models.TextField()),
                ('sign_count', models.PositiveIntegerField(default=0)),
                ('credential_type', models.CharField(blank=True, max_length=32)),
                ('aaguid', models.CharField(blank=True, max_length=64)),
                ('transports', models.JSONField(blank=True, default=list)),
                ('authenticator_attachment', models.CharField(blank=True, max_length=32)),
                ('device_type', models.CharField(blank=True, max_length=32)),
                ('backed_up', models.BooleanField(default=False)),
                ('user_agent', models.TextField(blank=True)),
                ('trusted_token_hash', models.CharField(blank=True, default='', max_length=128)),
                ('trusted_token_created_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_device_credentials', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_device_credentials', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username', 'status', '-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='pat_dev_user_status_idx')],
            },
        ),
    ]
