# Generated by Django 5.2.11 on 2026-03-16 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0015_deviceapprovalpolicy_staffdevicecredential"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientDataBackupSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                (
                    "schedule_mode",
                    models.CharField(
                        choices=[
                            ("DAILY", "1 per day"),
                            ("TWICE_DAILY", "2 per day (12:00 AM and 12:00 PM)"),
                            ("CUSTOM", "Custom timings"),
                        ],
                        default="DAILY",
                        max_length=16,
                    ),
                ),
                ("daily_time", models.TimeField(default=datetime.time(2, 0))),
                ("custom_times", models.JSONField(blank=True, default=list)),
                ("retention_count", models.PositiveIntegerField(default=30)),
                ("last_backup_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_backup_path",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "last_backup_status",
                    models.CharField(
                        choices=[
                            ("NEVER", "Never run"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                        ],
                        default="NEVER",
                        max_length=16,
                    ),
                ),
                (
                    "last_backup_trigger",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MANUAL", "Manual"),
                            ("SCHEDULED", "Scheduled"),
                            ("IMPORT_SAFETY", "Import safety"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("last_backup_error", models.TextField(blank=True, default="")),
                ("run_lock_until", models.DateTimeField(blank=True, null=True)),
                (
                    "run_lock_token",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
