# Generated by Django 5.2.11 on 2026-03-16 14:26

from django.db import migrations, models


def preserve_legacy_scheduled_backup_state(apps, schema_editor):
    PatientDataBackupSchedule = apps.get_model("patients", "PatientDataBackupSchedule")
    PatientDataBackupSchedule.objects.filter(
        last_daily_backup_at__isnull=True,
        last_backup_at__isnull=False,
        last_backup_trigger__in=["SCHEDULED", "DAILY_SCHEDULED"],
    ).update(last_daily_backup_at=models.F("last_backup_at"))


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0016_patientdatabackupschedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientdatabackupschedule",
            name="last_daily_backup_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientdatabackupschedule",
            name="last_monthly_backup_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientdatabackupschedule",
            name="last_yearly_backup_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patientdatabackupschedule",
            name="last_backup_trigger",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MANUAL", "Manual"),
                    ("DAILY_SCHEDULED", "Daily scheduled backup"),
                    ("MONTHLY_SCHEDULED", "Monthly scheduled backup"),
                    ("YEARLY_SCHEDULED", "Yearly scheduled backup"),
                    ("SCHEDULED", "Scheduled"),
                    ("IMPORT_SAFETY", "Import safety"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.RunPython(preserve_legacy_scheduled_backup_state, migrations.RunPython.noop),
    ]
