# Generated by Django 5.2.12 on 2026-03-21 14:32

from django.db import migrations, models


def backfill_case_subcategories(apps, schema_editor):
    Case = apps.get_model("patients", "Case")
    Case.objects.filter(category__name__iexact="Surgery", subcategory="").update(subcategory="GENERAL_SURGERY")
    Case.objects.filter(category__name__iexact="Medicine", subcategory="").update(subcategory="GENERAL_MEDICINE")


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0022_case_archived_at_case_archived_by_case_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('GENERAL_SURGERY', 'General Surgery'), ('ORTHOPEDICS', 'Orthopedics'), ('PLASTIC_SURGERY', 'Plastic Surgery'), ('PEDIATRIC_SURGERY', 'Pediatric Surgery'), ('UROLOGY', 'Urology'), ('ENT', 'ENT'), ('OTHER_SPECIALTY', 'Other Specialty'), ('GENERAL_MEDICINE', 'General Medicine'), ('PSYCHIATRY', 'Psychiatry'), ('CARDIOLOGY_ECHO', 'Cardiology (ECHO)'), ('PEDIATRIC', 'Pediatric'), ('MEDICAL_ONCOLOGY', 'Medical Oncology')], default='', max_length=40),
        ),
        migrations.RunPython(backfill_case_subcategories, migrations.RunPython.noop),
    ]
