# Generated by Django 5.2.12 on 2026-03-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0025_update_navbar_mockup_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='prefix',
            field=models.CharField(blank=True, choices=[('MR', 'Mr.'), ('MS', 'Ms.'), ('MRS', 'Mrs.')], default='', max_length=10),
        ),
    ]
