# Generated by Django 5.2.12 on 2026-03-22 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


PREFIX_LABELS = {
    "MR": "Mr.",
    "MS": "Ms.",
    "MRS": "Mrs.",
}


def _normalize_text(value):
    return " ".join((value or "").split()).strip()


def _build_patient_name(case_row):
    if _normalize_text(case_row.patient_name):
        return _normalize_text(case_row.patient_name)
    prefix_label = PREFIX_LABELS.get(case_row.prefix or "", "")
    parts = [prefix_label, _normalize_text(case_row.first_name), _normalize_text(case_row.last_name)]
    return " ".join(part for part in parts if part)


def backfill_patients_and_case_links(apps, schema_editor):
    Case = apps.get_model("patients", "Case")
    Patient = apps.get_model("patients", "Patient")
    RoleSetting = apps.get_model("patients", "RoleSetting")

    patients_by_uhid = {}
    for case_row in Case.objects.order_by("created_at", "id"):
        normalized_uhid = _normalize_text(case_row.uhid).upper()
        patient = patients_by_uhid.get(normalized_uhid)
        if patient is None:
            patient = Patient.objects.create(
                uhid=normalized_uhid,
                is_temporary_id=normalized_uhid.startswith("TMP-"),
                prefix=case_row.prefix or "",
                first_name=_normalize_text(case_row.first_name),
                last_name=_normalize_text(case_row.last_name),
                patient_name=_build_patient_name(case_row),
                gender=case_row.gender or "",
                date_of_birth=case_row.date_of_birth,
                place=_normalize_text(case_row.place),
                age=case_row.age,
                phone_number=_normalize_text(case_row.phone_number),
                alternate_phone_number=_normalize_text(case_row.alternate_phone_number),
                created_by=case_row.created_by,
            )
            patients_by_uhid[normalized_uhid] = patient
        Case.objects.filter(pk=case_row.pk).update(patient_id=patient.pk)

    RoleSetting.objects.filter(role_name="Admin").update(can_patient_merge=True)


def reverse_backfill_patients_and_case_links(apps, schema_editor):
    Case = apps.get_model("patients", "Case")
    Patient = apps.get_model("patients", "Patient")
    RoleSetting = apps.get_model("patients", "RoleSetting")

    Case.objects.update(patient_id=None)
    Patient.objects.all().delete()
    RoleSetting.objects.update(can_patient_merge=False)


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0027_alter_case_prefix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rolesetting',
            name='can_patient_merge',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='case',
            name='uhid',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(max_length=64, unique=True)),
                ('is_temporary_id', models.BooleanField(default=False)),
                ('prefix', models.CharField(blank=True, choices=[('MR', 'Mr.'), ('MS', 'Ms.'), ('MRS', 'Mrs.')], default='', max_length=3)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('patient_name', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(blank=True, choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('OTHER', 'Other'), ('UNKNOWN', 'Unknown')], max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=200)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=10)),
                ('alternate_phone_number', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patients', to=settings.AUTH_USER_MODEL)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_patients', to='patients.patient')),
            ],
            options={
                'ordering': ['patient_name', 'uhid'],
            },
        ),
        migrations.AddField(
            model_name='case',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='patients.patient'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['patient'], name='patients_ca_patient_504aca_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['first_name', 'last_name'], name='patients_pa_first_n_a142c0_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['patient_name'], name='patients_pa_patient_2373ab_idx'),
        ),
        migrations.RunPython(
            backfill_patients_and_case_links,
            reverse_backfill_patients_and_case_links,
        ),
    ]
