# Generated by Django 5.2.12 on 2026-03-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0028_rolesetting_can_patient_merge_alter_case_uhid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='ftnd',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='case',
            name='lscs',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
