# Generated by Django 5.2.12 on 2026-03-24 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0029_case_ftnd_case_lscs'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentconfig',
            name='starter_task_templates',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
