# Generated by Django 5.2.12 on 2026-04-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0034_rolesetting_can_task_reopen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='prefix',
            field=models.CharField(blank=True, choices=[('MR', 'Mr.'), ('MST', 'Master'), ('MS', 'Ms.'), ('MRS', 'Mrs.')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='patient',
            name='prefix',
            field=models.CharField(blank=True, choices=[('MR', 'Mr.'), ('MST', 'Master'), ('MS', 'Ms.'), ('MRS', 'Mrs.')], default='', max_length=3),
        ),
    ]
