# Generated by Django 5.2.12 on 2026-08-29 23:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_role_scopes(apps, schema_editor):
    RoleSetting = apps.get_model("patients", "RoleSetting")
    for role in RoleSetting.objects.all():
        if role.role_name in {"Admin", "Doctor"}:
            case_data_scope = "ALL"
        elif any(
            [
                role.can_case_create,
                role.can_case_edit,
                role.can_task_create,
                role.can_task_edit,
                role.can_note_add,
                role.can_manage_settings,
            ]
        ):
            case_data_scope = "ASSIGNED"
        else:
            case_data_scope = "NONE"
        RoleSetting.objects.filter(pk=role.pk).update(
            case_data_scope=case_data_scope,
            can_access_call_queue=role.can_note_add,
            can_intake_patient_lookup=role.can_case_create,
        )


def initialize_user_security_states(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    UserSecurityState = apps.get_model("patients", "UserSecurityState")
    UserSecurityState.objects.bulk_create(
        [UserSecurityState(user_id=user_id, auth_version=1) for user_id in User.objects.values_list("pk", flat=True)],
        ignore_conflicts=True,
    )


def validate_existing_vitals(apps, schema_editor):
    VitalEntry = apps.get_model("patients", "VitalEntry")
    invalid = VitalEntry.objects.filter(
        models.Q(bp_systolic__lt=70)
        | models.Q(bp_systolic__gt=240)
        | models.Q(bp_diastolic__lt=40)
        | models.Q(bp_diastolic__gt=140)
        | models.Q(pr__lt=30)
        | models.Q(pr__gt=220)
        | models.Q(spo2__lt=50)
        | models.Q(spo2__gt=100)
        | models.Q(weight_kg__lt=Decimal("30.0"))
        | models.Q(weight_kg__gt=Decimal("120.0"))
    ).count()
    if invalid:
        raise RuntimeError(
            f"Cannot add vital-sign constraints: {invalid} existing row(s) violate the approved ranges."
        )


def create_audit_append_only_trigger(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        """
        CREATE OR REPLACE FUNCTION patients_reject_audit_mutation()
        RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'patients_auditevent is append-only';
        END;
        $$ LANGUAGE plpgsql;
        CREATE TRIGGER patients_auditevent_append_only
        BEFORE UPDATE OR DELETE ON patients_auditevent
        FOR EACH ROW EXECUTE FUNCTION patients_reject_audit_mutation();
        """
    )


def drop_audit_append_only_trigger(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        """
        DROP TRIGGER IF EXISTS patients_auditevent_append_only ON patients_auditevent;
        DROP FUNCTION IF EXISTS patients_reject_audit_mutation();
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0036_remove_plaintext_password_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('category', models.CharField(choices=[('CLINICAL', 'Clinical'), ('IAM', 'Identity and access'), ('DATA', 'Data operation')], max_length=16)),
                ('action', models.CharField(max_length=80)),
                ('outcome', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('DENIED', 'Denied')], default='SUCCESS', max_length=16)),
                ('actor_user_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('actor_username', models.CharField(blank=True, max_length=150)),
                ('source', models.CharField(default='system', max_length=32)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('session_key_hash', models.CharField(blank=True, max_length=64)),
                ('source_ip_hash', models.CharField(blank=True, max_length=64)),
                ('device_credential_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('object_type', models.CharField(blank=True, max_length=80)),
                ('object_id', models.CharField(blank=True, max_length=80)),
                ('patient_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('case_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AuthenticationThrottleBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=24)),
                ('key_hash', models.CharField(max_length=64)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('window_started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryPatientIDSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_date', models.DateField(unique=True)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['allocation_date'],
            },
        ),
        migrations.CreateModel(
            name='UserSecurityState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_version', models.PositiveBigIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='rolesetting',
            name='can_access_call_queue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolesetting',
            name='can_intake_patient_lookup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolesetting',
            name='case_data_scope',
            field=models.CharField(choices=[('NONE', 'No case data'), ('ASSIGNED', 'Created or assigned cases'), ('ALL', 'All cases')], default='NONE', max_length=16),
        ),
        migrations.RunPython(backfill_role_scopes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='vitalentry',
            name='bp_diastolic',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(140)]),
        ),
        migrations.AlterField(
            model_name='vitalentry',
            name='bp_systolic',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(70), django.core.validators.MaxValueValidator(240)]),
        ),
        migrations.AlterField(
            model_name='vitalentry',
            name='pr',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(220)]),
        ),
        migrations.AlterField(
            model_name='vitalentry',
            name='spo2',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='vitalentry',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('30.0')), django.core.validators.MaxValueValidator(Decimal('120.0'))]),
        ),
        migrations.RunPython(validate_existing_vitals, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='vitalentry',
            constraint=models.CheckConstraint(condition=models.Q(('bp_systolic__isnull', True), ('bp_systolic__range', (70, 240)), _connector='OR'), name='vital_bp_sys_range'),
        ),
        migrations.AddConstraint(
            model_name='vitalentry',
            constraint=models.CheckConstraint(condition=models.Q(('bp_diastolic__isnull', True), ('bp_diastolic__range', (40, 140)), _connector='OR'), name='vital_bp_dia_range'),
        ),
        migrations.AddConstraint(
            model_name='vitalentry',
            constraint=models.CheckConstraint(condition=models.Q(('pr__isnull', True), ('pr__range', (30, 220)), _connector='OR'), name='vital_pr_range'),
        ),
        migrations.AddConstraint(
            model_name='vitalentry',
            constraint=models.CheckConstraint(condition=models.Q(('spo2__isnull', True), ('spo2__range', (50, 100)), _connector='OR'), name='vital_spo2_range'),
        ),
        migrations.AddConstraint(
            model_name='vitalentry',
            constraint=models.CheckConstraint(condition=models.Q(('weight_kg__isnull', True), ('weight_kg__range', (Decimal('30.0'), Decimal('120.0'))), _connector='OR'), name='vital_weight_range'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['category', 'action', '-occurred_at'], name='pat_audit_cat_action_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['actor_user_id', '-occurred_at'], name='pat_audit_actor_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['case_id', '-occurred_at'], name='pat_audit_case_idx'),
        ),
        migrations.AddIndex(
            model_name='authenticationthrottlebucket',
            index=models.Index(fields=['scope', 'blocked_until'], name='pat_auth_scope_blocked_idx'),
        ),
        migrations.AddConstraint(
            model_name='authenticationthrottlebucket',
            constraint=models.UniqueConstraint(fields=('scope', 'key_hash'), name='uniq_auth_throttle_scope_key'),
        ),
        migrations.AddField(
            model_name='usersecuritystate',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_state', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(initialize_user_security_states, migrations.RunPython.noop),
        migrations.RunPython(create_audit_append_only_trigger, drop_audit_append_only_trigger),
    ]
