# Generated by Django 6.1.1 on 2026-09-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0039_accessible_theme_interaction_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='anc_continue_follow_up',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='case',
            name='anc_outcome',
            field=models.CharField(blank=True, choices=[('delivery', 'Delivery'), ('loss_to_follow_up', 'Loss to follow-up'), ('referral', 'Referral'), ('other', 'Other resolution')], default='', max_length=24),
        ),
        migrations.AddField(
            model_name='case',
            name='anc_outcome_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='anc_outcome_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='anc_referral_destination',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
