# Generated by Django 6.1.1 on 2026-09-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0040_case_anc_continue_follow_up_case_anc_outcome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='reason',
            field=models.CharField(blank=True, db_default='', default='', max_length=500),
        ),
    ]
