# Generated by Django 6.1.1 on 2026-09-16 11:56

from django.db import migrations, models
from django.db.models import Q


def grant_phonebook_maintenance(apps, schema_editor):
    # Preserve existing managers and enable the explicitly requested Reception role.
    # Do not reset any other administrator-customized policy field.
    RoleSetting = apps.get_model('patients', 'RoleSetting')
    RoleSetting.objects.using(schema_editor.connection.alias).filter(
        Q(can_manage_settings=True) | Q(role_name='Reception')
    ).update(can_manage_phonebook=True)


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0044_patient_identity_enforce'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolesetting',
            name='can_manage_phonebook',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.RunPython(grant_phonebook_maintenance, migrations.RunPython.noop),
    ]
